sudo: false
language: generic
cache:
  directories:
  - "$HOME/.stack/"
  - "$HOME/.local/bin/"
  - ".stack-work/"
before_install:
- mkdir -p ~/.local/bin
- export PATH=$HOME/.local/bin:$PATH
- travis_retry curl -L https://www.stackage.org/stack/linux-x86_64 | tar xz --wildcards --strip-components=1 -C ~/.local/bin '*/stack'
install:
- stack --no-terminal test --only-dependencies
jobs:
  include:
    - stage: Run stack test
      script: stack --no-terminal test --fast
    - stage: Run stack test --pedantic
      script:
      - stack clean
      - stack --no-terminal test --fast --pedantic
    - stage: Run HLint
      script: curl -sL https://raw.github.com/ndmitchell/hlint/master/misc/travis.sh | sh -s .

notifications:
  email: false